// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQS-8uYMMpmXovLpiBD25jUPKdnDLtOU',
    appId: '1:179951568435:web:7a1345715ae34d07244546',
    messagingSenderId: '179951568435',
    projectId: 'primarybus',
    authDomain: 'primarybus.firebaseapp.com',
    storageBucket: 'primarybus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6B_fSovGMuyh31_tRYAy2dHWKauAqt_0',
    appId: '1:179951568435:android:bf591df53bf6e58d244546',
    messagingSenderId: '179951568435',
    projectId: 'primarybus',
    storageBucket: 'primarybus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHToD6lYYiVLMwe3ZXbIRVcPaBDNd_2BA',
    appId: '1:179951568435:ios:e51efadf459bdac6244546',
    messagingSenderId: '179951568435',
    projectId: 'primarybus',
    storageBucket: 'primarybus.appspot.com',
    iosClientId: '179951568435-9vl8jkvj5eust6tjh23eti893u4ea2r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.primaryBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHToD6lYYiVLMwe3ZXbIRVcPaBDNd_2BA',
    appId: '1:179951568435:ios:e51efadf459bdac6244546',
    messagingSenderId: '179951568435',
    projectId: 'primarybus',
    storageBucket: 'primarybus.appspot.com',
    iosClientId: '179951568435-9vl8jkvj5eust6tjh23eti893u4ea2r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.primaryBus',
  );
}
